### ISSUE TITLE
Starry延迟高，丢包严重

### ISSUE THREAD

**Issue by zeeler** [Captain-Alan/VPS-Recommendation#1]
申请了个HKLinux 1GB，Datacenter只有HK4可选，开通后，ping值170ms左右，丢包率30%(100个包)，我是广东电信100M，坐标深圳南山区，已经取消了服务并申请了退款(工作日支付宝大概1个小时内就收到了退款)，好坑爹啊！

**Comment by zeeler** [comment]
之前使用oneaisahost.com一直延迟很低，大概40ms左右，偶尔电信抽风时会丢包，就是价格比较贵，服务不好。
搬瓦匠bwh1.net也是延迟比较高，大概160ms；
之前GCE台湾区延迟很低，有20ms左右，但是最近突然延迟高了，估计绕道了。

**Comment by Captain-Alan** [comment]
我们公司的也是100M电信，测试了Starry和UFOVPS的香港VPS，ping值处在9ms左右，丢包率都处在2%左右，并没有出现30%的情况，不过我测试了Starry的Tokyo的VPS，ping值与丢包率都与你所说的数值都差不多，所以我判断可能是你购买的VPS所在地不在HK吧，也有可能是Starry欺骗客户给你布置的VPS地点是HK以外的城市。

**Comment by Captain-Alan** [comment]
我个人认为HK的机房越来越难满足我们的使用需求了，ping值虽低，但是水管太低，丢包率反而提高，挤到HK购买的VPS的人本就已经不少了，所以现在比较推荐台湾和日本的VPS，我使用的Tokyo的Vultr一直稳定如狗，每次测试时均没有过丢包现象，只是ping值在100左右，并不是特别满意；对于台湾的VPS，由于绝大多数的VPN供应商多是选择台湾的VPS，所以每隔一段时间GFW监测到境外IP连接人数过多时便会将特定IP及IP段一起封禁，对于我们购买VPS的个人用户必遭殃，因为我们的IP是固定IP，一般无法更换的，除非重新购买VPS获取新的IP，且新的VPS网段不处于GFW名单中，所以我依然看好Vultr。

**Comment by zeeler** [comment]
我ping了下Vultr，深圳电信，延迟没有低于150ms的，之前我申请的oneasiahost.com的只有40多，你可以试试 116.251.216.231

**Comment by Captain-Alan** [comment]
我使用的Vultr是Tokyo的，ping值的确是100ms左右（有线网络下）；
另外，台湾的VPS能用的时候的确稳定，就怕被封，你SG的站点速度的确不错（我在华南经台湾访问你的网站），ping值和丢包率都很好，只是国内访问你的网站不是很流畅，在能接收价格的范围内的话，还是建议你继续使用；
针对中国广泛地域的特点，境外VPS建站，人人都可高速访问，是不现实的，还是用国内便宜又有速度的阿里云/百度云/华为云和枫叶主机虚拟主机流畅（当然折腾VPS的个人用户并不全是建站）【枫叶主机的VPS很不错，又有线路优化，对于大多数地区是很好的选择，不过不是独立带宽（HK地区的VPS应该都很少有独立带宽），并不一定能满足性能级访问需求】；

最后，VPS/VPN/虚拟主机没有最好的，只有最合适自己需求的：
只是建站又不想去备案网站，可以考虑枫叶的虚拟主机；
只是用于VPN的，考虑用别人已经搭建好的VPN服务（我现在使用的[二师兄VPN终生用户](http://ershixiong1.mobi/home.action?ic=6475297BD0)就很不错），会便宜好多，windows用户可以使用ShadowsSocks服务+Proxifier来替代windows默认的VPN（国内windows的VPN服务已经沦陷）；
如果是因linux环境使用方便+搭建VPN+搭建站点+搭建云盘+其他各种折腾的意愿 而购买VPS，那就往贵的选，尤其可以考虑独立主机了，又或者可以根据不同的需求按年费分别购买相应合适的服务，其实综合各种服务的话也挺实惠的，这未必不会比性能级需求好。

**Comment by Captain-Alan** [comment]
还有一种技术型的建议就是，自己搭建线路，国内购买阿里大带宽的云服务器+Tokyo/台湾的大带宽VPS，自己建立直连，之前在一个地方见到这个需求是为了下载升级日版PS游戏机中的游戏和系统

**Comment by zeeler** [comment]
我用vps主要是用于ss，现在新加坡那个流量足够，带宽也够，在家里用智能电视看youtube用1080p完全无压力啊，很流畅
