### ISSUE TITLE
UFOVPS 并非CN2?

### ISSUE THREAD

**Issue by GF-Huang** [Captain-Alan/VPS-Recommendation#2]
![image](https://user-images.githubusercontent.com/4510984/33377847-dba16444-d54d-11e7-9df3-597b5588e597.png)

**Comment by Captain-Alan** [comment]
我之前在这篇文章中加入UFOVPS时（1年前），UFOVPS使用的是美国KT机房，且称接驳CN2，现在其官网已经说道『**美国PZ机房(Psychz)接驳中国优化线路**』

**Comment by Captain-Alan** [comment]
UFOVPS这家公司信誉还是很好的，而且主打香港的VPS
